In [3]:
import tensorflow.keras as k

(x, y), (xT, yT) = k.datasets.mnist.load_data()

In [26]:
from tensorflow.keras import layers
import numpy as np
model = k.models.Sequential()
N = 28**2
print(x.shape)

xShaped = x.reshape((x.shape[0], x.shape[1]**2)).astype(np.float32) / 255
yShaped = k.utils.to_categorical(y)
model.add(k.Input(shape=()))
model.add(layers.Dense(64,
                       activation='relu',
                      ))

(60000, 28, 28)
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
